/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-01-10 02:56:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.guest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("  <title>Aroma Shop - Home</title>\r\n");
      out.write("\t<link rel=\"icon\" href=\"img/Fevicon.png\" type=\"image/png\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/bootstrap/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/fontawesome/css/all.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"vendors/themify-icons/themify-icons.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/nice-select/nice-select.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/owl-carousel/owl.theme.default.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"vendors/owl-carousel/owl.carousel.min.css\">\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <main class=\"site-main\">\r\n");
      out.write("    \r\n");
      out.write("    <!--================ Hero banner start =================-->\r\n");
      out.write("    <section class=\"hero-banner\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row no-gutters align-items-center pt-60px\">\r\n");
      out.write("          <div class=\"col-5 d-none d-sm-block\">\r\n");
      out.write("            <div class=\"hero-banner__img\">\r\n");
      out.write("              <img class=\"img-fluid\" src=\"img/home/hero-banner.png\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-sm-7 col-lg-6 offset-lg-1 pl-4 pl-md-5 pl-lg-0\">\r\n");
      out.write("            <div class=\"hero-banner__content\">\r\n");
      out.write("              <h4>Shop is fun</h4>\r\n");
      out.write("              <h1>Browse Our Premium Product</h1>\r\n");
      out.write("              <p>Us which over of signs divide dominion deep fill bring they're meat beho upon own earth without morning over third. Their male dry. They are great appear whose land fly grass.</p>\r\n");
      out.write("              <a class=\"button button-hero\" href=\"#\">Browse Now</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--================ Hero banner start =================-->\r\n");
      out.write("\r\n");
      out.write("    <!--================ Hero Carousel start =================-->\r\n");
      out.write("    <section class=\"section-margin mt-0\">\r\n");
      out.write("      <div class=\"owl-carousel owl-theme hero-carousel\">\r\n");
      out.write("        <div class=\"hero-carousel__slide\">\r\n");
      out.write("          <img src=\"img/home/hero-slide1.png\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("          <a href=\"#\" class=\"hero-carousel__slideOverlay\">\r\n");
      out.write("            <h3>Wireless Headphone</h3>\r\n");
      out.write("            <p>Accessories Item</p>\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"hero-carousel__slide\">\r\n");
      out.write("          <img src=\"img/home/hero-slide2.png\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("          <a href=\"#\" class=\"hero-carousel__slideOverlay\">\r\n");
      out.write("            <h3>Wireless Headphone</h3>\r\n");
      out.write("            <p>Accessories Item</p>\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"hero-carousel__slide\">\r\n");
      out.write("          <img src=\"img/home/hero-slide3.png\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("          <a href=\"#\" class=\"hero-carousel__slideOverlay\">\r\n");
      out.write("            <h3>Wireless Headphone</h3>\r\n");
      out.write("            <p>Accessories Item</p>\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!--================ Hero Carousel end =================-->\r\n");
      out.write("\r\n");
      out.write("    <!-- ================ trending product section start ================= -->  \r\n");
      out.write("    <section class=\"section-margin calc-60px\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"section-intro pb-60px\">\r\n");
      out.write("          <p>Popular Item in the market</p>\r\n");
      out.write("          <h2>Trending <span class=\"section-intro__style\">Product</span></h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-6 col-lg-4 col-xl-3\">\r\n");
      out.write("            <div class=\"card text-center card-product\">\r\n");
      out.write("              <div class=\"card-product__img\">\r\n");
      out.write("                <img class=\"card-img\" src=\"img/product/product1.png\" alt=\"\">\r\n");
      out.write("                <ul class=\"card-product__imgOverlay\">\r\n");
      out.write("                  <li><button><i class=\"ti-search\"></i></button></li>\r\n");
      out.write("                  <li><button><i class=\"ti-shopping-cart\"></i></button></li>\r\n");
      out.write("                  <li><button><i class=\"ti-heart\"></i></button></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <p>Accessories</p>\r\n");
      out.write("                <h4 class=\"card-product__title\"><a href=\"single-product.html\">Quartz Belt Watch</a></h4>\r\n");
      out.write("                <p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6 col-lg-4 col-xl-3\">\r\n");
      out.write("            <div class=\"card text-center card-product\">\r\n");
      out.write("              <div class=\"card-product__img\">\r\n");
      out.write("                <img class=\"card-img\" src=\"img/product/product2.png\" alt=\"\">\r\n");
      out.write("                <ul class=\"card-product__imgOverlay\">\r\n");
      out.write("                  <li><button><i class=\"ti-search\"></i></button></li>\r\n");
      out.write("                  <li><button><i class=\"ti-shopping-cart\"></i></button></li>\r\n");
      out.write("                  <li><button><i class=\"ti-heart\"></i></button></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <p>Beauty</p>\r\n");
      out.write("                <h4 class=\"card-product__title\"><a href=\"single-product.html\">Women Freshwash</a></h4>\r\n");
      out.write("                <p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6 col-lg-4 col-xl-3\">\r\n");
      out.write("            <div class=\"card text-center card-product\">\r\n");
      out.write("              <div class=\"card-product__img\">\r\n");
      out.write("                <img class=\"card-img\" src=\"img/product/product3.png\" alt=\"\">\r\n");
      out.write("                <ul class=\"card-product__imgOverlay\">\r\n");
      out.write("                  <li><button><i class=\"ti-search\"></i></button></li>\r\n");
      out.write("                  <li><button><i class=\"ti-shopping-cart\"></i></button></li>\r\n");
      out.write("                  <li><button><i class=\"ti-heart\"></i></button></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <p>Decor</p>\r\n");
      out.write("                <h4 class=\"card-product__title\"><a href=\"single-product.html\">Room Flash Light</a></h4>\r\n");
      out.write("                <p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6 col-lg-4 col-xl-3\">\r\n");
      out.write("            <div class=\"card text-center card-product\">\r\n");
      out.write("              <div class=\"card-product__img\">\r\n");
      out.write("                <img class=\"card-img\" src=\"img/product/product4.png\" alt=\"\">\r\n");
      out.write("                <ul class=\"card-product__imgOverlay\">\r\n");
      out.write("                  <li><button><i class=\"ti-search\"></i></button></li>\r\n");
      out.write("                  <li><button><i class=\"ti-shopping-cart\"></i></button></li>\r\n");
      out.write("                  <li><button><i class=\"ti-heart\"></i></button></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <p>Decor</p>\r\n");
      out.write("                <h4 class=\"card-product__title\"><a href=\"single-product.html\">Room Flash Light</a></h4>\r\n");
      out.write("                <p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6 col-lg-4 col-xl-3\">\r\n");
      out.write("            <div class=\"card text-center card-product\">\r\n");
      out.write("              <div class=\"card-product__img\">\r\n");
      out.write("                <img class=\"card-img\" src=\"img/product/product5.png\" alt=\"\">\r\n");
      out.write("                <ul class=\"card-product__imgOverlay\">\r\n");
      out.write("                  <li><button><i class=\"ti-search\"></i></button></li>\r\n");
      out.write("                  <li><button><i class=\"ti-shopping-cart\"></i></button></li>\r\n");
      out.write("                  <li><button><i class=\"ti-heart\"></i></button></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <p>Accessories</p>\r\n");
      out.write("                <h4 class=\"card-product__title\"><a href=\"single-product.html\">Man Office Bag</a></h4>\r\n");
      out.write("                <p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6 col-lg-4 col-xl-3\">\r\n");
      out.write("            <div class=\"card text-center card-product\">\r\n");
      out.write("              <div class=\"card-product__img\">\r\n");
      out.write("                <img class=\"card-img\" src=\"img/product/product6.png\" alt=\"\">\r\n");
      out.write("                <ul class=\"card-product__imgOverlay\">\r\n");
      out.write("                  <li><button><i class=\"ti-search\"></i></button></li>\r\n");
      out.write("                  <li><button><i class=\"ti-shopping-cart\"></i></button></li>\r\n");
      out.write("                  <li><button><i class=\"ti-heart\"></i></button></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <p>Kids Toy</p>\r\n");
      out.write("                <h4 class=\"card-product__title\"><a href=\"single-product.html\">Charging Car</a></h4>\r\n");
      out.write("                <p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6 col-lg-4 col-xl-3\">\r\n");
      out.write("            <div class=\"card text-center card-product\">\r\n");
      out.write("              <div class=\"card-product__img\">\r\n");
      out.write("                <img class=\"card-img\" src=\"img/product/product7.png\" alt=\"\">\r\n");
      out.write("                <ul class=\"card-product__imgOverlay\">\r\n");
      out.write("                  <li><button><i class=\"ti-search\"></i></button></li>\r\n");
      out.write("                  <li><button><i class=\"ti-shopping-cart\"></i></button></li>\r\n");
      out.write("                  <li><button><i class=\"ti-heart\"></i></button></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <p>Accessories</p>\r\n");
      out.write("                <h4 class=\"card-product__title\"><a href=\"single-product.html\">Blutooth Speaker</a></h4>\r\n");
      out.write("                <p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("              </div> \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6 col-lg-4 col-xl-3\">\r\n");
      out.write("            <div class=\"card text-center card-product\">\r\n");
      out.write("              <div class=\"card-product__img\">\r\n");
      out.write("                <img class=\"card-img\" src=\"img/product/product8.png\" alt=\"\">\r\n");
      out.write("                <ul class=\"card-product__imgOverlay\">\r\n");
      out.write("                  <li><button><i class=\"ti-search\"></i></button></li>\r\n");
      out.write("                  <li><button><i class=\"ti-shopping-cart\"></i></button></li>\r\n");
      out.write("                  <li><button><i class=\"ti-heart\"></i></button></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <p>Kids Toy</p>\r\n");
      out.write("                <h4 class=\"card-product__title\"><a href=\"#\">Charging Car</a></h4>\r\n");
      out.write("                <p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- ================ trending product section end ================= -->  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ================ offer section start ================= --> \r\n");
      out.write("    <section class=\"offer\" id=\"parallax-1\" data-anchor-target=\"#parallax-1\" data-300-top=\"background-position: 20px 30px\" data-top-bottom=\"background-position: 0 20px\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-xl-5\">\r\n");
      out.write("            <div class=\"offer__content text-center\">\r\n");
      out.write("              <h3>Up To 50% Off</h3>\r\n");
      out.write("              <h4>Winter Sale</h4>\r\n");
      out.write("              <p>Him she'd let them sixth saw light</p>\r\n");
      out.write("              <a class=\"button button--active mt-3 mt-xl-4\" href=\"#\">Shop Now</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- ================ offer section end ================= --> \r\n");
      out.write("\r\n");
      out.write("    <!-- ================ Best Selling item  carousel ================= --> \r\n");
      out.write("    <section class=\"section-margin calc-60px\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"section-intro pb-60px\">\r\n");
      out.write("          <p>Popular Item in the market</p>\r\n");
      out.write("          <h2>Best <span class=\"section-intro__style\">Sellers</span></h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"owl-carousel owl-theme\" id=\"bestSellerCarousel\">\r\n");
      out.write("          <div class=\"card text-center card-product\">\r\n");
      out.write("            <div class=\"card-product__img\">\r\n");
      out.write("              <img class=\"img-fluid\" src=\"img/product/product1.png\" alt=\"\">\r\n");
      out.write("              <ul class=\"card-product__imgOverlay\">\r\n");
      out.write("                <li><button><i class=\"ti-search\"></i></button></li>\r\n");
      out.write("                <li><button><i class=\"ti-shopping-cart\"></i></button></li>\r\n");
      out.write("                <li><button><i class=\"ti-heart\"></i></button></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <p>Accessories</p>\r\n");
      out.write("              <h4 class=\"card-product__title\"><a href=\"single-product.html\">Quartz Belt Watch</a></h4>\r\n");
      out.write("              <p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"card text-center card-product\">\r\n");
      out.write("            <div class=\"card-product__img\">\r\n");
      out.write("              <img class=\"img-fluid\" src=\"img/product/product2.png\" alt=\"\">\r\n");
      out.write("              <ul class=\"card-product__imgOverlay\">\r\n");
      out.write("                <li><button><i class=\"ti-search\"></i></button></li>\r\n");
      out.write("                <li><button><i class=\"ti-shopping-cart\"></i></button></li>\r\n");
      out.write("                <li><button><i class=\"ti-heart\"></i></button></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <p>Beauty</p>\r\n");
      out.write("              <h4 class=\"card-product__title\"><a href=\"single-product.html\">Women Freshwash</a></h4>\r\n");
      out.write("              <p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"card text-center card-product\">\r\n");
      out.write("            <div class=\"card-product__img\">\r\n");
      out.write("              <img class=\"img-fluid\" src=\"img/product/product3.png\" alt=\"\">\r\n");
      out.write("              <ul class=\"card-product__imgOverlay\">\r\n");
      out.write("                <li><button><i class=\"ti-search\"></i></button></li>\r\n");
      out.write("                <li><button><i class=\"ti-shopping-cart\"></i></button></li>\r\n");
      out.write("                <li><button><i class=\"ti-heart\"></i></button></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <p>Decor</p>\r\n");
      out.write("              <h4 class=\"card-product__title\"><a href=\"single-product.html\">Room Flash Light</a></h4>\r\n");
      out.write("              <p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"card text-center card-product\">\r\n");
      out.write("            <div class=\"card-product__img\">\r\n");
      out.write("              <img class=\"img-fluid\" src=\"img/product/product4.png\" alt=\"\">\r\n");
      out.write("              <ul class=\"card-product__imgOverlay\">\r\n");
      out.write("                <li><button><i class=\"ti-search\"></i></button></li>\r\n");
      out.write("                <li><button><i class=\"ti-shopping-cart\"></i></button></li>\r\n");
      out.write("                <li><button><i class=\"ti-heart\"></i></button></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <p>Decor</p>\r\n");
      out.write("              <h4 class=\"card-product__title\"><a href=\"single-product.html\">Room Flash Light</a></h4>\r\n");
      out.write("              <p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"card text-center card-product\">\r\n");
      out.write("            <div class=\"card-product__img\">\r\n");
      out.write("              <img class=\"img-fluid\" src=\"img/product/product1.png\" alt=\"\">\r\n");
      out.write("              <ul class=\"card-product__imgOverlay\">\r\n");
      out.write("                <li><button><i class=\"ti-search\"></i></button></li>\r\n");
      out.write("                <li><button><i class=\"ti-shopping-cart\"></i></button></li>\r\n");
      out.write("                <li><button><i class=\"ti-heart\"></i></button></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <p>Accessories</p>\r\n");
      out.write("              <h4 class=\"card-product__title\"><a href=\"single-product.html\">Quartz Belt Watch</a></h4>\r\n");
      out.write("              <p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"card text-center card-product\">\r\n");
      out.write("            <div class=\"card-product__img\">\r\n");
      out.write("              <img class=\"img-fluid\" src=\"img/product/product2.png\" alt=\"\">\r\n");
      out.write("              <ul class=\"card-product__imgOverlay\">\r\n");
      out.write("                <li><button><i class=\"ti-search\"></i></button></li>\r\n");
      out.write("                <li><button><i class=\"ti-shopping-cart\"></i></button></li>\r\n");
      out.write("                <li><button><i class=\"ti-heart\"></i></button></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <p>Beauty</p>\r\n");
      out.write("              <h4 class=\"card-product__title\"><a href=\"single-product.html\">Women Freshwash</a></h4>\r\n");
      out.write("              <p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"card text-center card-product\">\r\n");
      out.write("            <div class=\"card-product__img\">\r\n");
      out.write("              <img class=\"img-fluid\" src=\"img/product/product3.png\" alt=\"\">\r\n");
      out.write("              <ul class=\"card-product__imgOverlay\">\r\n");
      out.write("                <li><button><i class=\"ti-search\"></i></button></li>\r\n");
      out.write("                <li><button><i class=\"ti-shopping-cart\"></i></button></li>\r\n");
      out.write("                <li><button><i class=\"ti-heart\"></i></button></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <p>Decor</p>\r\n");
      out.write("              <h4 class=\"card-product__title\"><a href=\"single-product.html\">Room Flash Light</a></h4>\r\n");
      out.write("              <p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"card text-center card-product\">\r\n");
      out.write("            <div class=\"card-product__img\">\r\n");
      out.write("              <img class=\"img-fluid\" src=\"img/product/product4.png\" alt=\"\">\r\n");
      out.write("              <ul class=\"card-product__imgOverlay\">\r\n");
      out.write("                <li><button><i class=\"ti-search\"></i></button></li>\r\n");
      out.write("                <li><button><i class=\"ti-shopping-cart\"></i></button></li>\r\n");
      out.write("                <li><button><i class=\"ti-heart\"></i></button></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <p>Decor</p>\r\n");
      out.write("              <h4 class=\"card-product__title\"><a href=\"single-product.html\">Room Flash Light</a></h4>\r\n");
      out.write("              <p class=\"card-product__price\">$150.00</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- ================ Best Selling item  carousel end ================= --> \r\n");
      out.write("\r\n");
      out.write("    <!-- ================ Blog section start ================= -->  \r\n");
      out.write("    <section class=\"blog\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"section-intro pb-60px\">\r\n");
      out.write("          <p>Popular Item in the market</p>\r\n");
      out.write("          <h2>Latest <span class=\"section-intro__style\">News</span></h2>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-6 col-lg-4 mb-4 mb-lg-0\">\r\n");
      out.write("            <div class=\"card card-blog\">\r\n");
      out.write("              <div class=\"card-blog__img\">\r\n");
      out.write("                <img class=\"card-img rounded-0\" src=\"img/blog/blog1.png\" alt=\"\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <ul class=\"card-blog__info\">\r\n");
      out.write("                  <li><a href=\"#\">By Admin</a></li>\r\n");
      out.write("                  <li><a href=\"#\"><i class=\"ti-comments-smiley\"></i> 2 Comments</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <h4 class=\"card-blog__title\"><a href=\"single-blog.html\">The Richland Center Shooping News and weekly shooper</a></h4>\r\n");
      out.write("                <p>Let one fifth i bring fly to divided face for bearing divide unto seed. Winged divided light Forth.</p>\r\n");
      out.write("                <a class=\"card-blog__link\" href=\"#\">Read More <i class=\"ti-arrow-right\"></i></a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-6 col-lg-4 mb-4 mb-lg-0\">\r\n");
      out.write("            <div class=\"card card-blog\">\r\n");
      out.write("              <div class=\"card-blog__img\">\r\n");
      out.write("                <img class=\"card-img rounded-0\" src=\"img/blog/blog2.png\" alt=\"\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <ul class=\"card-blog__info\">\r\n");
      out.write("                  <li><a href=\"#\">By Admin</a></li>\r\n");
      out.write("                  <li><a href=\"#\"><i class=\"ti-comments-smiley\"></i> 2 Comments</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <h4 class=\"card-blog__title\"><a href=\"single-blog.html\">The Shopping News also offers top-quality printing services</a></h4>\r\n");
      out.write("                <p>Let one fifth i bring fly to divided face for bearing divide unto seed. Winged divided light Forth.</p>\r\n");
      out.write("                <a class=\"card-blog__link\" href=\"#\">Read More <i class=\"ti-arrow-right\"></i></a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-6 col-lg-4 mb-4 mb-lg-0\">\r\n");
      out.write("            <div class=\"card card-blog\">\r\n");
      out.write("              <div class=\"card-blog__img\">\r\n");
      out.write("                <img class=\"card-img rounded-0\" src=\"img/blog/blog3.png\" alt=\"\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <ul class=\"card-blog__info\">\r\n");
      out.write("                  <li><a href=\"#\">By Admin</a></li>\r\n");
      out.write("                  <li><a href=\"#\"><i class=\"ti-comments-smiley\"></i> 2 Comments</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <h4 class=\"card-blog__title\"><a href=\"single-blog.html\">Professional design staff and efficient equipment youâll find we offer</a></h4>\r\n");
      out.write("                <p>Let one fifth i bring fly to divided face for bearing divide unto seed. Winged divided light Forth.</p>\r\n");
      out.write("                <a class=\"card-blog__link\" href=\"#\">Read More <i class=\"ti-arrow-right\"></i></a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- ================ Blog section end ================= -->  \r\n");
      out.write("\r\n");
      out.write("    <!-- ================ Subscribe section start ================= --> \r\n");
      out.write("    <section class=\"subscribe-position\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"subscribe text-center\">\r\n");
      out.write("          <h3 class=\"subscribe__title\">Get Update From Anywhere</h3>\r\n");
      out.write("          <p>Bearing Void gathering light light his eavening unto dont afraid</p>\r\n");
      out.write("          <div id=\"mc_embed_signup\">\r\n");
      out.write("            <form target=\"_blank\" action=\"https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01\" method=\"get\" class=\"subscribe-form form-inline mt-5 pt-1\">\r\n");
      out.write("              <div class=\"form-group ml-sm-auto\">\r\n");
      out.write("                <input class=\"form-control mb-1\" type=\"email\" name=\"EMAIL\" placeholder=\"Enter your email\" onfocus=\"this.placeholder = ''\" onblur=\"this.placeholder = 'Your Email Address '\" >\r\n");
      out.write("                <div class=\"info\"></div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <button class=\"button button-subscribe mr-auto mb-1\" type=\"submit\">Subscribe Now</button>\r\n");
      out.write("              <div style=\"position: absolute; left: -5000px;\">\r\n");
      out.write("                <input name=\"b_36c4fd991d266f23781ded980_aefe40901a\" tabindex=\"-1\" value=\"\" type=\"text\">\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- ================ Subscribe section end ================= --> \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  </main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
