/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-01-12 21:33:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/User/.m2/repository/org/apache/tiles/tiles-jsp/3.0.5/tiles-jsp-3.0.5.jar", Long.valueOf(1578743445265L));
    _jspx_dependants.put("jar:file:/C:/Users/User/.m2/repository/org/apache/tiles/tiles-jsp/3.0.5/tiles-jsp-3.0.5.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1411309930000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>string</title>\r\n");
      out.write("    <link rel=\"icon\" href=\"/img/Fevicon.png\" type=\"image/png\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/vendors/bootstrap/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/vendors/fontawesome/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/vendors/themify-icons/themify-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/vendors/linericon/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/vendors/owl-carousel/owl.theme.default.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/vendors/owl-carousel/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/vendors/nice-select/nice-select.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/vendors/nouislider/nouislider.css\">\r\n");
      out.write("    <script src=\"/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function CatgPage(catg){\r\n");
      out.write("        var f=document.paging;\r\n");
      out.write("        f.catg.value=catg;\r\n");
      out.write("        f.action=\"/aroma/category\";\r\n");
      out.write("        f.method=\"post\";\r\n");
      out.write("        f.submit();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"padding-top: 0px;\">\r\n");
      out.write("<!--================ Start Header Menu Area =================-->\r\n");
      out.write("<header class=\"header_area\">\r\n");
      out.write("    <div class=\"main_menu\">\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <a class=\"navbar-brand logo_h\" href=\"/\"><img src=\"/img/logo.png\" alt=\"\"></a>\r\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\r\n");
      out.write("                        aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse offset\" id=\"navbarSupportedContent\">\r\n");
      out.write("                    <ul class=\"nav navbar-nav menu_nav mr-auto\" style=\"margin-left: 65px;\">\r\n");
      out.write("                        <li class=\"nav-item active\"><a class=\"nav-link\" href=\"/\">Home</a></li>\r\n");
      out.write("                        <li class=\"nav-item submenu dropdown\">\r\n");
      out.write("\r\n");
      out.write("                                <a href=\"/aroma/mypage\" class=\"nav-link dropdown-toggle\">My Page</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"nav-item submenu dropdown\">\r\n");
      out.write("                            ");
      out.write("\r\n");
      out.write("                                <form name=\"paging\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"catg\"/>\r\n");
      out.write("                                    <input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            <a href=\"#\" onclick='CatgPage(0)' class=\"nav-link dropdown-toggle\">Category</a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\" onclick='CatgPage(1)'>한국시</a></li>\r\n");
      out.write("                                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\" onclick='CatgPage(2)'>외국시</a></li>\r\n");
      out.write("                                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\" onclick='CatgPage(3)'>인물 에세이</a></li>\r\n");
      out.write("                                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\" onclick='CatgPage(4)'>여행 에세이</a></li>\r\n");
      out.write("                                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\" onclick='CatgPage(5)'>성공 에세이</a></li>\r\n");
      out.write("                                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\" onclick='CatgPage(6)'>독서 에세이</a></li>\r\n");
      out.write("                                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\" onclick='CatgPage(7)'>명상 에세이</a></li>\r\n");
      out.write("                                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\" onclick='CatgPage(8)'>그림/포토 에세이</a></li>\r\n");
      out.write("                                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\" onclick='CatgPage(9)'>연애/사랑 에세이</a></li>\r\n");
      out.write("                                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\" onclick='CatgPage(10)'>삶의 지혜/명언</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("                    <ul class=\"nav-shop\">\r\n");
      out.write("                        <li class=\"nav-item\"><button><i class=\"ti-search\"></i></button></li>\r\n");
      out.write("                        <li class=\"nav-item\"><button><i class=\"ti-shopping-cart\"></i><span class=\"nav-shop__circle\">3</span></button> </li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"button button-header\" href=\"#\">Login / Register</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<!--================ End Header Menu Area =================-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
