/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-01-10 12:53:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.aroma;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.naming.Context;

public final class category_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/kosta/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1576132841486L));
    _jspx_dependants.put("jar:file:/C:/Users/kosta/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.naming.Context");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fend_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fend_005fbegin.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("  <title>Aroma Shop - Category</title>\r\n");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("\r\n");
      out.write("    .pixel-radio:checked::after {\r\n");
      out.write("      -webkit-animation: click-wave 0.65s;\r\n");
      out.write("      -moz-animation: click-wave 0.65s;\r\n");
      out.write("      animation: click-wave 0.65s;\r\n");
      out.write("      background: #384aeb;\r\n");
      out.write("      content: '';\r\n");
      out.write("      display: block;\r\n");
      out.write("      width: 15px;\r\n");
      out.write("      height: 15px;\r\n");
      out.write("      border-radius: 50%;\r\n");
      out.write("      position: relative;\r\n");
      out.write("      z-index: 2;\r\n");
      out.write("      opacity: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @import url(\"https://fonts.googleapis.com/css?family=Roboto:400,300\");\r\n");
      out.write("    .pagination-container {\r\n");
      out.write("      color: #2c3e50;\r\n");
      out.write("      font-family: 'Roboto', sans-serif;\r\n");
      out.write("      font-weight: 400;\r\n");
      out.write("      margin: 15px auto;\r\n");
      out.write("      padding-right: 40px;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    .pagination {\r\n");
      out.write("      position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    .pagination a {\r\n");
      out.write("      position: relative;\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      color: #2c3e50;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      font-size: 1.2rem;\r\n");
      out.write("      padding: 8px 16px 10px;\r\n");
      out.write("    }\r\n");
      out.write("    .pagination a:before {\r\n");
      out.write("      z-index: -1;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      content: \"\";\r\n");
      out.write("      top: 0;\r\n");
      out.write("      left: 0;\r\n");
      out.write("      background-color: #2c3e50;\r\n");
      out.write("      border-radius: 24px;\r\n");
      out.write("      -webkit-transform: scale(0);\r\n");
      out.write("      transform: scale(0);\r\n");
      out.write("      transition: all 0.2s;\r\n");
      out.write("    }\r\n");
      out.write("    .pagination a:hover,\r\n");
      out.write("    .pagination a .pagination-active {\r\n");
      out.write("      color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("    .pagination a:hover:before,\r\n");
      out.write("    .pagination a .pagination-active:before {\r\n");
      out.write("      -webkit-transform: scale(1);\r\n");
      out.write("      transform: scale(1);\r\n");
      out.write("    }\r\n");
      out.write("    .pagination .pagination-active {\r\n");
      out.write("      color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("    .pagination .pagination-active:before {\r\n");
      out.write("      -webkit-transform: scale(1);\r\n");
      out.write("      transform: scale(1);\r\n");
      out.write("    }\r\n");
      out.write("    .pagination-newer {\r\n");
      out.write("      margin-right: 50px;\r\n");
      out.write("    }\r\n");
      out.write("    .pagination-older {\r\n");
      out.write("      margin-left: 50px;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("  <script>\r\n");
      out.write("    $(function(){\r\n");
      out.write("\r\n");
      out.write("      var CatgIdx=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CatgIdx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("      var startPage=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${startPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("      var maxPage=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${maxPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("      var curPage;\r\n");
      out.write("      var pageInfo;\r\n");
      out.write("\r\n");
      out.write("      $(\"#category li input[id=CatgIdx]\").prop('checked',true);\r\n");
      out.write("      alert($(\"#category li input[id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CatgIdx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("]\").attr('id'));\r\n");
      out.write("      //AJAX기능\r\n");
      out.write("      function bookAjax(CatgIdx,PageNum){\r\n");
      out.write("        $.ajax({\r\n");
      out.write("          async: false,\r\n");
      out.write("          url : \"/catgCall\", //서버요청주소\r\n");
      out.write("          type : \"get\",//요청방식 (get,post,patch,delete,put)\r\n");
      out.write("          dataType : \"json\",//서버가 보내온 데이터 타입 (text, html, xml, json)\r\n");
      out.write("          data : \"CatgIdx=\"+CatgIdx+\"&PageNum=\"+PageNum,//서버에게 보내는 parameter정보\r\n");
      out.write("          success : function(result){\r\n");
      out.write("            $(\"#bookCard\").empty();\r\n");
      out.write("\r\n");
      out.write("            $.each(result[0], function(index, item){\r\n");
      out.write("              var Img = item.bookImg;\r\n");
      out.write("              var Title = item.bookTitle;\r\n");
      out.write("              var Price = item.bookPrice;\r\n");
      out.write("              var CatgName = item.category.catgName;\r\n");
      out.write("\r\n");
      out.write("              var str = \" <div class=\\\"col-md-6 col-lg-4\\\">\\n\" +\r\n");
      out.write("                      \"                <div class=\\\"card text-center card-product\\\">\\n\" +\r\n");
      out.write("                      \"                  <div class=\\\"card-product__img\\\">\\n\" +\r\n");
      out.write("                      \"                    <img class=\\\"card-img\\\" src=\\\"\"+Img+\"\\\" alt=\\\"\\\">\\n\" +\r\n");
      out.write("                      \"                    <ul class=\\\"card-product__imgOverlay\\\">\\n\" +\r\n");
      out.write("                      \"                      <li><button><i class=\\\"ti-search\\\"></i></button></li>\\n\" +\r\n");
      out.write("                      \"                      <li><button><i class=\\\"ti-shopping-cart\\\"></i></button></li>\\n\" +\r\n");
      out.write("                      \"                      <li><button><i class=\\\"ti-heart\\\"></i></button></li>\\n\" +\r\n");
      out.write("                      \"                    </ul>\\n\" +\r\n");
      out.write("                      \"                  </div>\\n\" +\r\n");
      out.write("                      \"                  <div class=\\\"card-body\\\">\\n\" +\r\n");
      out.write("                      \"                    <p>\"+CatgName+\"</p>\\n\" +\r\n");
      out.write("                      \"                    <h4 class=\\\"card-product__title\\\"><a href=\\\"#\\\">\"+Title+\"</a></h4>\\n\" +\r\n");
      out.write("                      \"                    <p class=\\\"card-product__price\\\">\"+Price+\"</p>\\n\" +\r\n");
      out.write("                      \"                  </div>\\n\" +\r\n");
      out.write("                      \"                </div>\\n\" +\r\n");
      out.write("                      \"              </div>\";\r\n");
      out.write("              $('#bookCard').append(str);\r\n");
      out.write("              pageInfo = result[1];\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("          } , //성공했을때\r\n");
      out.write("          error : function(request){\r\n");
      out.write("          // alert(request.responseText);\r\n");
      out.write("          }// 실패했을때\r\n");
      out.write("        });\r\n");
      out.write("        startPage = pageInfo[0];\r\n");
      out.write("        maxPage = pageInfo[1];\r\n");
      out.write("        curPage = pageInfo[2];\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      //페이지 버튼\r\n");
      out.write("      $(document).on('click','.pagination-inner a',function(){\r\n");
      out.write("    // $('.pagination-inner a').on('click', function() {\r\n");
      out.write("      $(this).siblings().removeClass('pagination-active');\r\n");
      out.write("      $(this).addClass('pagination-active');\r\n");
      out.write("\r\n");
      out.write("      CatgIdx = $(\"#category li input:checked\").attr('id');\r\n");
      out.write("      var PageNum = $(\".pagination-active\").text();\r\n");
      out.write("      bookAjax(CatgIdx,PageNum);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    //카테고리 버튼\r\n");
      out.write("    $(\"#category li input\").on('click',function(){\r\n");
      out.write("      // $(\".pagination-active\").removeClass();\r\n");
      out.write("      // $(\".pagination-inner a:first\").addClass('pagination-active');\r\n");
      out.write("\r\n");
      out.write("      CatgIdx = $(this).attr('id');\r\n");
      out.write("      // var PageNum = $(\".pagination-active\").text();\r\n");
      out.write("      var PageNum = 1;\r\n");
      out.write("      bookAjax(CatgIdx,PageNum);\r\n");
      out.write("\r\n");
      out.write("      $(\".pagination-inner\").empty();\r\n");
      out.write("      var doneLoop = false;\r\n");
      out.write("      for(var i = startPage; i <= maxPage; i++){\r\n");
      out.write("        if(doneLoop==false){\r\n");
      out.write("          if(i == curPage){\r\n");
      out.write("            $(\".pagination-inner\").append(\"<a class='pagination-active' href='#ㅇㅅㅇ'>\"+i+\"</a>\");\r\n");
      out.write("          } else {\r\n");
      out.write("            $(\".pagination-inner\").append(\"<a href=\\\"#ㅇㅅㅇ\\\">\"+i+\"</a>\");\r\n");
      out.write("          }\r\n");
      out.write("          if(i==startPage+9){\r\n");
      out.write("            doneLoop = true;\r\n");
      out.write("          }\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // PREV, NEXT 버튼\r\n");
      out.write("    $(document).on('click','.pagination-older,.pagination-newer',function(){\r\n");
      out.write("      var PageNum = $(\".pagination-active\").text();\r\n");
      out.write("      if($(this).text() == 'PREV'){\r\n");
      out.write("        PageNum = PageNum*1 - 1;\r\n");
      out.write("        if(PageNum < 1){\r\n");
      out.write("          alert(\"이전 페이지가 존재하지 않습니다.\");\r\n");
      out.write("          return 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $('.pagination-active').prev().addClass('pagination-active');\r\n");
      out.write("        $('.pagination-active').next().removeClass('pagination-active');\r\n");
      out.write("\r\n");
      out.write("        if(PageNum == startPage-1) {\r\n");
      out.write("          bookAjax(CatgIdx, PageNum);\r\n");
      out.write("\r\n");
      out.write("          $(\".pagination-inner\").empty();\r\n");
      out.write("          var doneLoop = false;\r\n");
      out.write("          for (var i = startPage; i <= maxPage; i++) {\r\n");
      out.write("\r\n");
      out.write("            if (doneLoop == false) {\r\n");
      out.write("              if (i == PageNum) {\r\n");
      out.write("                $(\".pagination-inner\").append(\"<a class='pagination-active' href='#ㅇㅅㅇ'>\" + i + \"</a>\");\r\n");
      out.write("              } else {\r\n");
      out.write("                $(\".pagination-inner\").append(\"<a href=\\\"#ㅇㅅㅇ\\\">\" + i + \"</a>\");\r\n");
      out.write("              }\r\n");
      out.write("              if (i == startPage + 9) {\r\n");
      out.write("                doneLoop = true;\r\n");
      out.write("              }\r\n");
      out.write("            }\r\n");
      out.write("          }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("      } else if ($(this).text() == 'NEXT'){\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        PageNum = PageNum*1 + 1;\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        if(PageNum > maxPage){\r\n");
      out.write("          alert(\"다음 페이지가 존재하지 않습니다.\");\r\n");
      out.write("          return 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        bookAjax(CatgIdx,PageNum);\r\n");
      out.write("\r\n");
      out.write("        $(\".pagination-inner\").empty();\r\n");
      out.write("        var doneLoop=false;\r\n");
      out.write("        for(var i = startPage; i <= maxPage; i++){\r\n");
      out.write("\r\n");
      out.write("          if(doneLoop==false){\r\n");
      out.write("            if(i == PageNum){\r\n");
      out.write("              $(\".pagination-inner\").append(\"<a class='pagination-active' href='#ㅇㅅㅇ'>\"+i+\"</a>\");\r\n");
      out.write("            } else {\r\n");
      out.write("              $(\".pagination-inner\").append(\"<a href=\\\"#ㅇㅅㅇ\\\">\"+i+\"</a>\");\r\n");
      out.write("            }\r\n");
      out.write("            if(i==startPage+9){\r\n");
      out.write("              doneLoop = true;\r\n");
      out.write("            }\r\n");
      out.write("          }\r\n");
      out.write("        }\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      bookAjax(CatgIdx,PageNum);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- ================ start banner area ================= -->\t\r\n");
      out.write("\t<section class=\"blog-banner-area\" id=\"category2\">\r\n");
      out.write("\t\t<div class=\"container h-100\">\r\n");
      out.write("\t\t\t<div class=\"blog-banner\">\r\n");
      out.write("\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t<h1>Shop Category</h1>\r\n");
      out.write("\t\t\t\t\t<nav aria-label=\"breadcrumb\" class=\"banner-breadcrumb\">\r\n");
      out.write("            <ol class=\"breadcrumb\">\r\n");
      out.write("              <li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\r\n");
      out.write("              <li class=\"breadcrumb-item active\" aria-current=\"page\">Shop Category</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </nav>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- ================ end banner area ================= -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- ================ category section start ================= -->\t\t  \r\n");
      out.write("  <section class=\"section-margin--small mb-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-xl-3 col-lg-4 col-md-5\">\r\n");
      out.write("          <div class=\"sidebar-categories\">\r\n");
      out.write("            <div class=\"head\">Browse Categories</div>\r\n");
      out.write("            <ul class=\"main-categories\">\r\n");
      out.write("              <li class=\"common-filter\">\r\n");
      out.write("                <form action=\"#\">\r\n");
      out.write("                  <ul id=\"category\">\r\n");
      out.write("                    <li class=\"filter-list\"><input class=\"pixel-radio\" type=\"radio\" id=\"0\" name=\"catg\" checked><label for=\"0\">전체보기<span> (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[10]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</span></label></li>\r\n");
      out.write("                    <li class=\"filter-list\"><input class=\"pixel-radio\" type=\"radio\" id=\"1\" name=\"catg\"><label for=\"1\">한국시<span> (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[0]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</span></label></li>\r\n");
      out.write("                    <li class=\"filter-list\"><input class=\"pixel-radio\" type=\"radio\" id=\"2\" name=\"catg\"><label for=\"2\">외국시<span> (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[1]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</span></label></li>\r\n");
      out.write("                    <li class=\"filter-list\"><input class=\"pixel-radio\" type=\"radio\" id=\"3\" name=\"catg\"><label for=\"3\">인물 에세이<span> (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[2]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</span></label></li>\r\n");
      out.write("                    <li class=\"filter-list\"><input class=\"pixel-radio\" type=\"radio\" id=\"4\" name=\"catg\"><label for=\"4\">여행 에세이<span> (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[3]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</span></label></li>\r\n");
      out.write("                    <li class=\"filter-list\"><input class=\"pixel-radio\" type=\"radio\" id=\"5\" name=\"catg\"><label for=\"5\">성공 에세이<span> (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[4]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</span></label></li>\r\n");
      out.write("                    <li class=\"filter-list\"><input class=\"pixel-radio\" type=\"radio\" id=\"6\" name=\"catg\"><label for=\"6\">독서 에세이<span> (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[5]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</span></label></li>\r\n");
      out.write("                    <li class=\"filter-list\"><input class=\"pixel-radio\" type=\"radio\" id=\"7\" name=\"catg\"><label for=\"7\">명상 에세이<span> (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[6]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</span></label></li>\r\n");
      out.write("                    <li class=\"filter-list\"><input class=\"pixel-radio\" type=\"radio\" id=\"8\" name=\"catg\"><label for=\"8\">그림/포토 에세이<span> (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[7]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</span></label></li>\r\n");
      out.write("                    <li class=\"filter-list\"><input class=\"pixel-radio\" type=\"radio\" id=\"9\" name=\"catg\"><label for=\"9\">연애/사랑 에세이<span> (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[8]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</span></label></li>\r\n");
      out.write("                    <li class=\"filter-list\"><input class=\"pixel-radio\" type=\"radio\" id=\"10\" name=\"catg\"><label for=\"10\">삶의 지혜/명언<span> (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list[9]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</span></label></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </form>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"sidebar-filter\">\r\n");
      out.write("            <div class=\"top-filter-head\">Product Filters</div>\r\n");
      out.write("            <div class=\"common-filter\">\r\n");
      out.write("              <div id=\"slider\">슬라이더 들어갈 곳</div>\r\n");
      out.write("              <!--<div class=\"head\">Price</div>\r\n");
      out.write("              <div class=\"price-range-area\">\r\n");
      out.write("                <div id=\"price-range\"></div>\r\n");
      out.write("                <div class=\"value-wrapper d-flex\">\r\n");
      out.write("                  <div class=\"price\">Price:</div>\r\n");
      out.write("                  <span>$</span>\r\n");
      out.write("                  <div id=\"lower-value\"></div>\r\n");
      out.write("                  <div class=\"to\">to</div>\r\n");
      out.write("                  <span>$</span>\r\n");
      out.write("                  <div id=\"upper-value\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>-->\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-xl-9 col-lg-8 col-md-7\">\r\n");
      out.write("          <!-- Start Filter Bar -->\r\n");
      out.write("          <div class=\"filter-bar d-flex flex-wrap align-items-center\">\r\n");
      out.write("            <div class=\"sorting mr-auto\">\r\n");
      out.write("              <select>\r\n");
      out.write("                <option value=\"1\">가나다 순</option>\r\n");
      out.write("                <option value=\"1\">가나다 역순</option>\r\n");
      out.write("                <option value=\"1\">출간일 순</option>\r\n");
      out.write("              </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"sorting\" style=\"margin-right: 5px;\">\r\n");
      out.write("              <select>\r\n");
      out.write("                <option value=\"1\">제목별</option>\r\n");
      out.write("                <option value=\"1\">저자별</option>\r\n");
      out.write("                <option value=\"1\">출판사별</option>\r\n");
      out.write("              </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("              <div class=\"input-group filter-bar-search\">\r\n");
      out.write("                <input type=\"text\" placeholder=\"Search\">\r\n");
      out.write("                <div class=\"input-group-append\">\r\n");
      out.write("                  <button type=\"button\"><i class=\"ti-search\"></i></button>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- End Filter Bar -->\r\n");
      out.write("          <!-- Start Best Seller -->\r\n");
      out.write("          <section class=\"lattest-product-area pb-40 category-list\">\r\n");
      out.write("            <div class=\"row\" id=\"bookCard\">\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <nav class=\"pagination-container\">\r\n");
      out.write("            <div class=\"pagination\">\r\n");
      out.write("              <a class=\"pagination-newer\" href=\"#ㅇㅅㅇ\">PREV</a>\r\n");
      out.write("              <span class=\"pagination-inner\">\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("              <a class=\"pagination-older\" href=\"#ㅇㅅㅇ\">NEXT</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </nav>\r\n");
      out.write("          </section>\r\n");
      out.write("          <!-- End Best Seller -->\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </section>\r\n");
      out.write("\t<!-- ================ category section end ================= -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- ================ top product area start ================= -->\t\r\n");
      out.write("\t<section class=\"related-product-area\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"section-intro pb-60px\">\r\n");
      out.write("        <p>Popular Item in the market</p>\r\n");
      out.write("        <h2>Top <span class=\"section-intro__style\">Product</span></h2>\r\n");
      out.write("      </div>\r\n");
      out.write("\t\t\t<div class=\"row mt-30\">\r\n");
      out.write("        <div class=\"col-sm-6 col-xl-3 mb-4 mb-xl-0\">\r\n");
      out.write("          <div class=\"single-search-product-wrapper\">\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"/img/product/product-sm-1.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                  <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                  <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"/img/product/product-sm-2.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"/img/product/product-sm-3.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-sm-6 col-xl-3 mb-4 mb-xl-0\">\r\n");
      out.write("          <div class=\"single-search-product-wrapper\">\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"/img/product/product-sm-4.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                  <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                  <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"/img/product/product-sm-5.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"/img/product/product-sm-6.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-sm-6 col-xl-3 mb-4 mb-xl-0\">\r\n");
      out.write("          <div class=\"single-search-product-wrapper\">\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"/img/product/product-sm-7.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                  <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                  <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"/img/product/product-sm-8.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"/img/product/product-sm-9.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-sm-6 col-xl-3 mb-4 mb-xl-0\">\r\n");
      out.write("          <div class=\"single-search-product-wrapper\">\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"/img/product/product-sm-1.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                  <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                  <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"/img/product/product-sm-2.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"single-search-product d-flex\">\r\n");
      out.write("              <a href=\"#\"><img src=\"/img/product/product-sm-3.png\" alt=\"\"></a>\r\n");
      out.write("              <div class=\"desc\">\r\n");
      out.write("                <a href=\"#\" class=\"title\">Gray Coffee Cup</a>\r\n");
      out.write("                <div class=\"price\">$170.00</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- ================ top product area end ================= -->\t\t\r\n");
      out.write("\r\n");
      out.write("\t<!-- ================ Subscribe section start ================= -->\t\t  \r\n");
      out.write("  <section class=\"subscribe-position\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"subscribe text-center\">\r\n");
      out.write("        <h3 class=\"subscribe__title\">Get Update From Anywhere</h3>\r\n");
      out.write("        <p>Bearing Void gathering light light his eavening unto dont afraid</p>\r\n");
      out.write("        <div id=\"mc_embed_signup\">\r\n");
      out.write("          <form target=\"_blank\" action=\"https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01\" method=\"get\" class=\"subscribe-form form-inline mt-5 pt-1\">\r\n");
      out.write("            <div class=\"form-group ml-sm-auto\">\r\n");
      out.write("              <input class=\"form-control mb-1\" type=\"email\" name=\"EMAIL\" placeholder=\"Enter your email\" onfocus=\"this.placeholder = ''\" onblur=\"this.placeholder = 'Your Email Address '\" >\r\n");
      out.write("              <div class=\"info\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button class=\"button button-subscribe mr-auto mb-1\" type=\"submit\">Subscribe Now</button>\r\n");
      out.write("            <div style=\"position: absolute; left: -5000px;\">\r\n");
      out.write("              <input name=\"b_36c4fd991d266f23781ded980_aefe40901a\" tabindex=\"-1\" value=\"\" type=\"text\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\t<!-- ================ Subscribe section end ================= -->\t\t  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/aroma/category.jsp(370,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /WEB-INF/views/aroma/category.jsp(370,16) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/aroma/category.jsp(370,16) '${booklist}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${booklist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/aroma/category.jsp(370,16) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write('\r');
            out.write('\n');
            out.write("\r\n");
            out.write("              <div class=\"col-md-6 col-lg-4\">\r\n");
            out.write("                <div class=\"card text-center card-product\">\r\n");
            out.write("                  <div class=\"card-product__img\">\r\n");
            out.write("                    <img class=\"card-img\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.bookImg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"\">\r\n");
            out.write("                    <ul class=\"card-product__imgOverlay\">\r\n");
            out.write("                      <li><button><i class=\"ti-search\"></i></button></li>\r\n");
            out.write("                      <li><button><i class=\"ti-shopping-cart\"></i></button></li>\r\n");
            out.write("                      <li><button><i class=\"ti-heart\"></i></button></li>\r\n");
            out.write("                    </ul>\r\n");
            out.write("                  </div>\r\n");
            out.write("                  <div class=\"card-body\">\r\n");
            out.write("                    <p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.category.catgName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("                    <h4 class=\"card-product__title\"><a href=\"#\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.bookTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></h4>\r\n");
            out.write("                    <p class=\"card-product__price\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.bookPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("                  </div>\r\n");
            out.write("                </div>\r\n");
            out.write("              </div>\r\n");
            out.write("            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/aroma/category.jsp(536,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("doneLoop");
      // /WEB-INF/views/aroma/category.jsp(536,20) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/aroma/category.jsp(536,20) 'false'",_jsp_getExpressionFactory().createValueExpression("false",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/aroma/category.jsp(537,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("i");
      // /WEB-INF/views/aroma/category.jsp(537,20) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${startPage}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /WEB-INF/views/aroma/category.jsp(537,20) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${maxPage}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /WEB-INF/views/aroma/category.jsp(537,20) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                      ");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("\r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/aroma/category.jsp(538,22) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not doneLoop}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("                          ");
          if (_jspx_meth_c_005fchoose_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("                        ");
          if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("                      ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("                            ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("                          ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/aroma/category.jsp(541,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i eq curPage}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                              <a class=\"pagination-active\" href=\"#ㅇㅅㅇ\">");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fwhen_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("</a>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
      // /WEB-INF/views/aroma/category.jsp(542,71) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                              <a href=\"#ㅇㅅㅇ\">");
          if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fotherwise_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("</a>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /WEB-INF/views/aroma/category.jsp(545,45) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/aroma/category.jsp(548,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.count eq 10}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                          ");
          if (_jspx_meth_c_005fset_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/aroma/category.jsp(549,26) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("doneLoop");
      // /WEB-INF/views/aroma/category.jsp(549,26) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/aroma/category.jsp(549,26) 'true'",_jsp_getExpressionFactory().createValueExpression("true",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }
}
